spring:
  application:
    name: backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      cottongallery:
        backend: debug
    org:
      springframework:
        security: DEBUG


jwt:
  secret: ${JWT_SECRET:OtItGKqtKQiR1loQhhVkfZAnzMfoNmQgH9pEdKt4nSQ=}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS:3600}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS:604800}
  authorization-header-access: AccessToken
  authorization-header-refresh: RefreshToken

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3000, http://localhost:5173}
  methods: ${ALLOWED_METHODS:GET, POST, PUT, DELETE, OPTIONS, PATCH}

file:
  path: /app/resources/