spring:
  application:
    name: backend

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      "[hibernate.SQL]": debug

jwt:
  header: Authorization
  secret: ${JWT_SECRET:default-secret-key}
  token-validity-in-seconds: 86400
  tokenPrefix: Bearer
