spring:
  application:
    name: backend

  profiles:
    active: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      cottongallery:
        backend: debug
    org:
      springframework:
        security: DEBUG


jwt:
  secret: OtItGKqtKQiR1loQhhVkfZAnzMfoNmQgH9pEdKt4nSQ=
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  authorization-header-access: AccessToken
  authorization-header-refresh: RefreshToken

allowed:
  origins: http://localhost:3000, http://localhost:5173
  methods: GET, POST, PUT, DELETE, OPTIONS, PATCH

file:
  path: /app/resources/

aws:
  bucket-name: