spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/yourDatabaseName
    username: yourUsername
    password: yourPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled: ALWAYS
