# AWS 환경에서 실행할 때 사용할 설정 파일
spring:
  datasource:
    url: "jdbc-secretsmanager:postgresql://${RDS_ENDPOINT}/${DB_NAME}"
    username: ${username}
    password: ${password}
    driver-class-name: com.amazonaws.secretsmanager.jdbc.AWSSecretsManagerDriver

  data:
    redis:
      host: ${ELASTICACHE_HOST}
      port: ${ELASTICACHE_PORT}
      password: ${ELASTICACHE_PASSWORD}