spring:
  application:
    name: backend

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      springframework:
        security: DEBUG


jwt:
  secret: OtItGKqtKQiR1loQhhVkfZAnzMfoNmQgH9pEdKt4nSQ=
  token-validity-in-seconds: 3600

allowed:
  origins: http://localhost:3000, http://localhost:5173
  methods: GET, POST, PUT, DELETE, OPTIONS