spring:
  application:
    name: backend

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        highlight_sql: true

  output:
    ansi:
      enabled: ALWAYS
